contents.burnt_fuel = {
  index: 4,
  caption: "Postępowanie z wypalonym paliwem",
  text: ''+
  '<p id="burnt_fuel">Na cykl życia paliwa dla reaktora jądrowego składa się wiele etapów, począwszy od wydobycia uranu po składowanie wypalonego paliwa. W jego trakcie, paliwo po wydobyciu z ziemi jest przetwarzane w formę możliwą do użycia w reaktorach jądrowych. Po projektowym okresie pracy paliwa, zostaje ono następnie przekształcone do postaci bezpiecznej w przechowywaniu. W trakcie cyklu paliwowego jest też możliwe odzyskiwanie materiałów rozszczepialnych z zużytego paliwa w celu późniejszego wykorzystania.</p>'+
  '<h1>Przechowalnie tymczasowe</h1>'+
  '<p>Wypalone paliwo po opuszczeniu rdzenia zostaje zanurzone w wodzie w celu odebrania ciepła wydzielanego w trakcie rozpadu radionuklidów w nim zawartych. W tym celu w pobliżu reaktora buduje się specjalnie do tego przeznaczone baseny. Elementy paliwowe są umieszczane w specjalnych stojakach wykonanych z materiałów absorbujących neutrony (np. z <a href="http://pl.wikipedia.org/wiki/Boral">boralu</a>), które mają za zadanie wygaszenie reakcji łańcuchowej. Rozmieszczenie stojaków jest tak dobrane, aby zapobiec osiągnięciu masy krytycznej, a w efekcie zapobiec samopodtrzymującej się reakcji rozszczepienia. Baseny przechowalnicze wymagają stałego monitorowania warunków w jakich znajdują się pręty paliwowe: temperatury oraz składu powietrza. Woda pod wpływem promieniowania ulega <a href="http://pl.wikipedia.org/wiki/Chemia_radiacyjna#Radioliza_wody">radiolizie</a>, co powoduje wydzielanie się wodoru i tlenu, a gromadzący się wodór stwarza zagrożenie wybuchem.</p>'+
  '<h1>Transport</h1>'+
  '<p>Po czasie spędzonym w repozytoriach, paliwo jest transportowane pomiędzy reaktorem, a centralnym repozytorium, bądź placówką zajmującą się przetwarzaniem odpadów radioaktywnych w specjalnych pojemnikach (rys. 1).</p>'+
  '<div class="thumbnail">'+
    '<img src="img/castor.gif" alt="castor" class="img-thumbnail" width="50%"/>'+
    '<div class="caption">Rys. 1. Metalowy pojemnik CASTOR typu 440/84 <a name="b_decom"></a>.</div>'+
  '</div>'+
  '<p>Głównym zadaniem pojemnika CASTOR jest zapewnienie ochrony otoczenia przed promieniowaniem oraz odprowadzanie ciepła z paliwa. Dodatkowo, pojemnik taki musi być odporny przed uszkodzeniami mechanicznymi. Przykładowe testy jakim poddaje się te przechowalniki są przedstawione na filmie 1. Materiałami konstrukcyjnym dla beczki CASTOR mogą być: kuta stal, <a href="http://pl.wikipedia.org/wiki/Żeliwo_sferoidalne">żeliwo sferoidalne</a> albo struktura wielowarstwowa ze stali i ołowiu. Jest ona wypełniona wewnątrz metalowym rusztowaniem zapewniającym wytrzymałość konstrukcji oraz podkrytyczność dla zachodzących wewnątrz reakcji. </p>'+
  '<div class="thumbnail">'+
    '<iframe width="420" height="315" src="http://www.youtube.com/embed/YW-LUf815I8?rel=0" frameborder="0" allowfullscreen></iframe>'+
    '<div class="caption">Film. 1. Materiał obrazujący rygorystyczne testy jakim zostają poddane pojemniki CASTOR tj. upadki z wysokości do 40m i sprawdziany wytrzymałości przy temperaturze -40&deg;C.</div>'+
  '</div>'+
  '<h1>Reprocessing</h1>'+
  '<p><i>Reprocessing</i> jest to procedura wyodrębniania rozszczepialnych nuklidów z wypalonego paliwa jądrowego. Pierwotnie, <i>reprocessing</i> był używany wyłącznie do wyodrębniania plutonu w celu produkcji broni jądrowej. W raz z rozwojem energetyki jądrowej, pluton zaczął być odzyskiwany do produkcji paliwa jądrowego <a href="http://en.wikipedia.org/wiki/MOX_nuclear_fuel">MOX</a>.</p>'+
  '<h2>Usuwanie powłok ochronnych</h2>'+
  '<p>Pierwszym etapem przetwarzania wypalonego paliwa jądrowego jest usuwanie powłok w elementach paliwowych. Jest to wykonywane za pomocą dwóch metod: chemicznej, oraz mechanicznej. </p>'+
  '<h3>Separacja mechaniczna</h3>'+
  '<p>Elementy paliwowe na początku są rozbierane, a następnie przetwarzane są znajdujące się tam pastylki lub kapsułki. Najczęściej elementy paliwowe składają się połączonych prętów - metalowych rurek (zazwyczaj wykonanych ze stopu cyrkonu, ze względu na dużą odporność na korozję oraz niską absorpcję neutronów) wypełnionych pastylkami z proszku UO<sub>2</sub>. W VHTR, elementy paliwowe są zbudowane z kapsułek TRISO, grafitu oraz odpowiednich spajaczy. W trakcie separacji mechanicznej są kruszone kule, czy to pręty paliwowe, aby uzyskać dostęp do kapsułek TRISO.</p>'+
  '<h3>Separacja chemiczna</h3>'+
  '<p>Pierwszym krokiem w trakcie przetwarzania kapsułek TRISO jest usunięcie zewnętrznej powłoki węglowej. Można tego dokonać za pomocą procesu wypalania kapsułek (wtedy węgiel zostanie związany w molekuły CO<sub>2</sub>), reakcji z parą wodną (produkowany jest CO i H<sub>2</sub>) lub reakcji z ciekłym NaOH (produkowany jest CO<sub>2</sub> lub CO i H<sub>2</sub>). Problemem w tym rozwiązaniu jest postępowanie z aktywowanym węglem <sup>14</sup>C który musi zostać usunięty z wyprodukowanych gazów, przed emisją do atmosfery. Proces ten może być wykorzystany do produkcji wodoru na skalę przemysłową.</p>'+
  '<p>Powyższe metody generalnie pozostawiają warstę SiC kapsułki nietkniętą. Może być ona usunięta poprzez fluoryzację (produkowany jest CF), reakcję w ciekłej soli NaNO<sub>3</sub> lub Na<sub>2</sub>CO<sub>3</sub> (uwalniane jest CO<sub>2</sub>) bądź rozpuszczenie w kwasie fosforowym H<sub>3</sub>PO<sub>4</sub> (wytwarzany jest CO i CO<sub>2</sub>).</p> '+
  '<p>Wewnętrzne warstwy węglowe mogą zostać usunięte w taki sam sposób, jak warstwy zewnętrzne. Rdzeń kapsułki jest rozpuszczany przez kwas azotowy HNO<sub>3</sub> (produkowane są tlenki azotu NO<sub>x</sub>). W trakcie pozbywania się wewnętrznej warstwy węglowej oraz rdzenia, uwalniane są gazy szlachetne będące produktami rozpadu (Kr i Xe).</p>'+
  '<h2>PUREX</h2>'+
  '<p><a href="http://en.wikipedia.org/wiki/PUREX">PUREX</a> (<i>ang.</i> Plutionum Uranium Extraction) jest procesem pozwalającym na wyodrębnienie uranu, plutonu oraz <a href="http://pl.wikipedia.org/wiki/Transuranowce">transuranowców</a> (TRU) powstałych w trakcie wypalania paliwa.  W trakcie tego procesu za pomocą rozpuszczalników organicznych (<a href="http://pl.wikipedia.org/wiki/Fosforan_tributylu">fosforan tributylu</a>), z rdzenia kapsułek paliwowych tworzy się <a href="http://pl.wikipedia.org/wiki/Związki_kompleksowe">związki kompleksowe</a> zawierające uran i pluton, które są strącane - lżejsze produkty rozpadu i inne transuranowce pozostają w roztworze. Z tak powstałego osadu pluton jest wymywany za pomocą <a href="http://pl.wikipedia.org/wiki/Kwas_sulfaminowy">kwasu sulfaminowego</a>. W ten sposób można oddzielić poszczególne pierwiastki, których część może zostać umieszczona z powrotem w paliwie jądrowym w celu dalszego wypalenia.</p>'+
  '<h1>Recykling paliwa w HTGR</h1>'+
  '<p>Reaktory wysokotemperaturowe dają możliwość umieszczenia wśród kapsułek paliwowych z niskowzbogaconym uranem, także te wypełnione tlenkami transuranowców pochodzących z reprocessingu. Są one umieszczane w centralnym rejonie rdzenia, gdzie są napromieniowywane przez dodatkowe 6 lat, zanim zostaną składowane w repozytorium odpadów. W procesie tego typu możliwe jest zniszczenie ponad 97% <sup>239</sup>Pu pochodzącego z niskowzbogaconego paliwa oraz ponad 59% masy transuranowców. W tym cyklu paliwowym, elementy paliwowe zawierające transuranowce są umieszczane wewnątrz środkowego reflektora neutronów. Na rys. 2 jest przedstawiony przepływ masy w procesie wypalania paliwa w HTGR.</p>'+
  '<div class="thumbnail">'+
    '<img src="img/mass_flow_advanced_fuel_cycle.png" alt="Przepływ masy - cykl paliwowy" class="img-thumbnail" width="80%"/>'+
    '<div class="caption">Rys. 2. Przepływ masy w trakcie recyklingu paliwa w reaktorze typu PR-HTGR. Znaczenia skrótów: DU - zubożony uran, NU - uran naturalny, RU - uran po reprocessingu, Enr - procedura wzbogacania, Fab - procedura tworzenia paliwa, UREX - procedura ekstrakcji uranu, <span class="nowrap">TRU - transuranowce</span>, FP - produkty rozpadu <a name="b_fchtgr"></a>.</div>'+
  '</div>'+
  '<p>PR-HTGR (Partial Recycling - High Temperature Gas Reactor) jest wypełniany paliwem niskowzbogaconym (LEU - <i>ang.</i> low enriched uranium) oraz zawierającym transuranowce (TRU). 90% produkowanej energii cieplnej pochodzi z paliwa LEU. Zużyte paliwo LEU jest poddawane reprocessingowi, a odzyskane w ten sposób paliwo TRU jest dopalane (~600 GWd/t) w trakcie pojedynczego przejścia przez rdzeń PR-HTGR. Zużyte kapsułki TRISO z TRU są następnie składowane do repozytoriów geologicznych. Uran odzyskany z wypalonego LEU zawiera ok. 3,5% <sup>235</sup>U i jest używany do produkcji kapsułek z LEU. Pozwala to zmniejszyć zapotrzebowanie na naturalny uran w tym procesie. Zaletą tego cyklu paliwowego jest to, że zużyte kapsułki z TRU są doskonałą postacią do składowania w repozytoriach geologicznych. Ich warstwy grafitowe i ceramiczne są odporne na korozję co pozwala im przetrwać nienaruszone przez długi okres czasu wystarczający do wygaszenia pozostałej aktywności radionuklidów w nich zamkniętych. </p>'+
  '<h1>Składowanie paliwa</h1>'+
  '<h2>Wstępne przygotowanie paliwa</h2>'+
  '<h3>Separacja i transmutacja</h3>'+
  '<p>Paliwo jądrowe po projektowym czasie wypalania wewnątrz reaktora jest poddawane szeregowi procesów, zanim zostanie umieszczone w repozytorium geologicznym. Poprzez separację mechaniczną i chemiczną są oddzielane poszczególne radioizotopy. W celu zmniejszenia <a href="http://pl.wikipedia.org/wiki/Radiotoksyczno%C5%9B%C4%87">radiotoksyczności</a> produkowanych odpadów, długożyciowe radionuklidy są poddawane procesowi transmutacji. W jego trakcie dokonuje się ich naświetlania neutronami w reaktorze lub akceleratorze (wiązka protonów uderza w tarczę, a następnie w wyniku <a href="http://pl.wikipedia.org/wiki/Spalacja">spalacji</a> są emitowane neutrony bombardujące fragment). Szybkie neutrony (E > 100 keV) wywołują rozpad jąder, ale w przeciwieństwie do reakcji zachodzących w tradycyjnych reaktorach, ustaje ona po zaniku wiązki.</p>'+
  '<h3>Formowanie</h3>'+
  '<p>Dalszym etapem przekształcania paliwa jest przekształcenie jego do formy, która będzie bezpieczna w transporcie oraz zajmowała jak najmniejszy rozmiar przestrzenny. Pierwszym krokiem jest spopielenie odpadów w temperaturach rzędu 1000 &deg;C  - umożliwia to zmniejszenie jego objętości nawet <span class="nowrap">100-krotnie</span>. Następnie są one zamykane  w odpowiednich pojemnikach. Odpady o niskiej aktywności są zamykane w metalowych beczkach - używane prasy w tym procesie umożliwiają na zmniejszenie objętości od 3 do 6 razy. W przypadku odpadów w formie stałych fragmentów, ścieków lub żeli, cementuje się je w metalowych pojemnikach. Odpady o najwyższej aktywności wymagają uformowania w nierozpuszczalny, stabilny i odporny na czynniki zewnętrzne element w postaci ciała stałego. Do tego celu używa się <a href="http://pl.wikipedia.org/wiki/Witryfikacja">witryfikacji</a>. Witryfikacja polega na zalewaniu ich szkłem borowo-krzemowym. Zaletą tego rozwiązania jest trwałość szkła - jest ono w stanie wytrzymać w tej postaci tysiące lat. Obecny bor ma duży przekrój czynny na wychwyt neutronów.</p>'+
  '<h2>Repozytoria geologiczne</h2>'+
  '<p>Pojemniki z odpadami w zależności od aktywności są składowane w repozytoriach na (w przypadku średnio i nisko aktywnych odpadów) lub pod powierzchnią ziemi. Podziemne składowiska odpadów o wysokiej aktywności, są projektowane na składowanie dużych ilości odpadów przez długi czas. Znajdują się zazwyczaj na głębokościach pomiędzy 250m a 1000m i zakłada się je w rejonach w których występują stabilne formacje geologiczne, takie jak skały, złoża soli oraz glina. Ważne jest aby zapewnić izolację repozytorium od otoczenia: obecność wody w repozytorium może wywołać korozję, a następnie wyciek radioaktywnych substancji.</p>'+
  '<h1>Analiza odpadów</h1>'+
  '<p>Paliwo jądrowe na każdym z etapów przetwarzania wymaga monitorowania składu izotopowego. Dokonuje się tego w jeden z dwóch sposobów: za pomocą analizy niedestrukcyjnej lub destrukcyjnej. Ten pierwszy rodzaj pozwala na zbadanie rozkładu przestrzennego radioizotopów w wypalonym paliwie poprzez obserwację spontanicznego lub wymuszonego promieniowania jonizującego (poprzez naświetlanie wiązką neutronów badanego elementu). Do charakteryzacji w tym trybie, używa się trzech metod: <a href="http://pl.wikipedia.org/wiki/Spektroskopia_gamma">spektrometrii gamma</a>, spektrometrii neutronowej oraz <a href="http://pl.wikipedia.org/wiki/Kalorymetria">kalorymetrii</a> (ilość wydzielanego ciepła pozwala określić aktywność paliwa). Analiza destrukcyjna, jest o wiele dokładniejsza w stosunku do niedestrukcyjnej, w jej trakcie wybiera się z pojemnika fragment wypalonego paliwa i przetwarza się tak, aby otrzymać jednolitą próbkę Następnie poprzez spektrometrię, alfa, beta i gamma oraz spektrometrię masową można w bardzo dokładny sposób określić skład izotopowy wypalonego paliwa.</p>',
  bibliography: {
    decom: '<a href="http://link.springer.com/referenceworkentry/10.1007%2F978-0-387-98149-9_27/fulltext.html#Fig14_27">Cumo M. <i>Decommmissioning of Nuclear Plants</i></a>',
    fchtgr: '<a href="http://www.academia.edu/4400824/Advanced_Fuel_Cycle_Scenarios_for_High_Temperature_Gas_Reactors">Choi, H. <i>Advanced Fuel Cycle Scenarios for High Temperature Gas Reactors.</i> Annals of Nuclear Energy 31 (2011) pp. 2338 - 2349</a>',
    eras: '<a href="http://link.springer.com/chapter/10.1007%2F978-90-481-2383-4_9#"> Ghosh, Tushar K. and Prelas, Mark A. <i>Energy Resources and Systems</i> 2009, pp 453-647</a>',
    triso_p: '<a href="http://aprs.ornl.gov/~webworks/cppr/y2003/rpt/114586.pdf">Del Cul G. D. et al <i>TRISO-Coated Fuel Processing to Support High Temperature Gas-Cooled Reactors</i></a>'
  }
  // Podstawowy cykl paliwowy
  // - zuzyte paliwo -> urex/pyro (adnotacja do artykulu o przetwarzaniu TRISO)
  // - transmutacja dlugozyciowych radionuklidow
  // - metody formowania: spopielanie i zamykanie w pojemnikach / innych formach
  // - repozytoria
  // analiza odpadów
  // budowa pr-htgr i wykorzystywane paliwo (uzywanie ponowne TRU)
  // 
};