contents.hydrogen_production = {
  index: 6,
  caption: "Produkcja wodoru",
  text: '<p id="hydrogen_production">Wodór ma duże znaczenie dla przemysłu petrochemicznego. Obecnie jego największym zastosowaniem jest przetwarzanie paliw kopalnych oraz produkcja amoniaku. Jest on także ekologicznym paliwem - w trakcie spalania wytwarza się tylko para wodna. Do obecnie stosowanych metod produkcji wodoru należą: <a href="http://pl.wikipedia.org/wiki/Reforming_parowy">reforming parowy</a>, <a href="http://en.wikipedia.org/wiki/Partial_oxidation">częściowe utlenianie węglowodorów</a>, <a href="http://en.wikipedia.org/wiki/Kværner-process">reforming plazmowy</a>, <a href="http://pl.wikipedia.org/wiki/Gazyfikacja_węgla">gazyfikacja węgla</a>, elektroliza wody, <a href="http://pl.wikipedia.org/wiki/Termoliza">termoliza wody</a>, <a href="http://en.wikipedia.org/wiki/Thermochemical_cycle">cykl termochemiczny</a>, reakcja żelazokrzemu z wodą, <a href="http://en.wikipedia.org/wiki/Biological_hydrogen_production_(Algae)">metody biologiczne</a>, <a href="http://en.wikipedia.org/wiki/Photocatalytic_water_splitting">fotokatalityczna separacja wody</a> i  <a href="http://en.wikipedia.org/wiki/Fermentative_hydrogen_production">fermentacja</a>. Większość z metod chemicznych wymaga podgrzewania substratów do temperatury ok. 1000 &deg;C. Z tego powodu atrakcyjnym ekonomicznie rozwiązaniem jest umieszczanie fabryk wodoru w pobliżu elektrowni jądrowych opartych na reaktorach wysokotemperaturowych. Poniżej zostały opisane metody, które mogą zostać użyte do produkcji wodoru z wykorzystaniem ciepła pochodzącego z VHTR.</p>'+
  '<h1>Reforming parowy</h1>'+
  '<p>Reforming parowy metanu jest najtańszym i najpopularniejszym procesem wykorzystywanym do produkcji wodoru na dużą skalę. W jego trakcie na mikroporowatej krzemowej membranie z dodatkiem katalizatora niklowego zachodzą następujące reakcje:<br/>CH<sub>4</sub> + H<sub>2</sub>O &harr; CO + 3H<sub>2</sub><br/>CO + H<sub>2</sub>O &harr; CO<sub>2</sub> + H<sub>2</sub><br/>CH<sub>4</sub> + 2H<sub>2</sub>O &harr; CO<sub>2</sub> + 4H<sub>2</sub>.<br/>Proces ten jest <a href="http://pl.wikipedia.org/wiki/Reakcja_endotermiczna">endotermiczny</a> i jest przeprowadzany w temperaturze ok. 800 &degC. Minusem tego rozwiązania jest wykorzystanie metanu, który jest już paliwem wysokiej jakości i jest surowcem nieodnawialnym. Reforming parowy wiąże się także z emisją dwutlenku węgla. W perspektywie czasu, metoda ta będzie wycofywana, na rzecz nowocześniejszych rozwiązań.</p>'+
  '<h1>Gazyfikacja węgla</h1>'+
  '<p></p>'+
  '<h1>Elektroliza</h1>'+
  '<p>Elektroliza wody polega na dekompozycji cząsteczek H<sub>2</sub>O na tlen (O<sub>2</sub>) i wodór (H<sub>2</sub>) za pomocą prądu płynącego przez wodę. Do dwóch metalowych płytek umieszczonych w wodzie zostaje podłączone napięcie stałe. Po włączeniu zasilania, wodór będzie wydzielał się na katodzie, a tlen na anodzie. Ilość wymaganej energii do <a href="http://pl.wikipedia.org/wiki/Dysocjacja_elektrolityczna">zdysocjowania</a> cząsteczek wody zmienia się wraz z temperaturą (rys. 1).'+
  '<div class="thumbnail">'+
    '<img src="img/h2o_gibbs.png" alt="Energia dysocjacji gram-mola wody" class="img-thumbnail" width="70%"/>'+
    '<div class="caption">Rys. 1. Wykres energii dysocjacji gram-mola wody w funkcji temperatury. <a name="b_doe_elec"></a>.</div>'+
  '</div>'+
  'Widać, że koszt energetyczny zdysocjowania gram-mola wody (a za tym idzie wytworzenia wodoru) spada wraz z temperaturą. Przeprowadzanie tego procesu w temperaturze 800 &deg;C pozwala na zmniejszenie ilości użytej energii elektrycznej i zwiększenie opłacalności produkcji wodoru.</p>'+
  '<h1>Cykl termochemiczny</h1>'+
  '<p>Bezpośrednia termoliza wody wymaga temperatur wyższych niż 4000 &deg;C. Cykl termochemiczny pozwala na rozłożenie cząsteczek wody na wodór i tlen przy znacznie mniejszych temperaturach. W trakcie reakcji chemicznych woda dysocjuje na związki tlenu i wodoru, które później są rozdzielane za pomocą ciepła lub elektryczności. Wśród obecnie istniejących cykli termochemicznych, najbardziej wydajny jest cykl bazujący na siarce i jodzie.</p>'+
  '<p>Poniższe trzy reakcje są używane do produkcji wodoru:<br/>I<sub>1</sub> + SO<sub>2</sub> &rarr; 2 HI + H<sub>2</sub>SO<sub>4</sub> (120 &deg;C)<br/>2 H<sub>2</sub>SO<sub>4</sub> &rarr; 2 SO<sub>2</sub> + 2 H<sub>2</sub>O + O<sub>2</sub> (830 &deg;C)<br/>1 HI &rarr; I<sub>2</sub> + H<sub>2</sub> (450 &deg;C).<br/>Zaletami cyklu S-I są m.in.: przystosowanie do pracy ciągłej, zamknięty system bez produktów ubocznych (poza tlenem i wodorem). Wadą tego rozwiązania jest stosowanie zaawansowanych materiałów odpornych na korozję.</p>',
  bibliography: {
    h_wiki: '<a href="http://en.wikipedia.org/wiki/Hydrogen_production"><i>Hydrogen production</i> - Wikipedia The Free Encyclopedia</a>',
    vhtr_rep: '<a href="http://large.stanford.edu/courses/2013/ph241/kallman1/docs/chapin.pdf"><i>A Very High Temperature Reactor: A Technical Summary</i></a>',
    linde_e: '<a href="http://onlinelibrary.wiley.com/doi/10.1002/aic.10215/full">T. Tsuru, K. Yamaguchi, T. Yoshioka, M. Asaeda <i>Methane steam reforming by microporous catalytic membrane reactors</i></a>',
    doe_elec: '<a href="http://www1.eere.energy.gov/solar/pdfs/doctor.pdf"><i>U.S. DOE high-temperature electrolysis</i></a>',
    tch_wiki: '<a href="http://en.wikipedia.org/wiki/Sulfur–iodine_cycle"><i>Sulfur-Iodine cycle</i> - Wikipedia The Free Encyclopedia</a>'
  }
};