contents.materials = {
  index: 3,
  caption: "Materiały konstrukcyjne",
  text: '<p id="materials">Materiały wykorzystywane do budowy VHTR musza być w stanie wytrzymywać wysokie temperatury oraz duże strumienie neutronów. Wartości tych parametrów są znacznie wyższe niż w przypadku LWR (<i>ang.</i> Light Water Reactor), co wymaga opracowania nowych rozwiązań dla reaktorów wysokotemperaturowych. Wyższe temperatury będą powodować zwiększoną dyfuzję atomów oraz ilość reakcji chemicznych na powierzchni w materiałach stosowanych w VHTR. Wyższy strumień neutronów będzie powodował większą ilość dyslokacji i transmutacji w elementach konstrukcyjnych. Wszystkie te efekty mają wpływ na mikrostrukturę oraz właściwości tych materiałów. </p>'+
    '<h1>Zbiornik ciśnieniowy reaktora</h1>'+
    '<p>Dobór materiału z którego ma być wykonany zbiornik ciśnieniowy reaktora (<i>ang.</i> RPV -  Reactor Pressure Vessel) jest kompromisem pomiędzy kosztem, a bezpieczeństwem VHTR. Chociaż wylot gazów z reaktora osiąga temperaturę rzędu 1000&deg;C, zbiornik może być utrzymywany w niższej temperaturze przez hel z wylotu układu chłodzącego. Szczytowa temperatura RPV w przypadku awarii musi znajdować się w zakresie, który nie spowoduje uszkodzenia zbiornika. Może być regulowana poprzez rozmiar RPV, gęstość mocy w rdzeniu lub całkowitą moc reaktora. Wybór konkretnego materiału o danej wytrzymałości temperaturowej zbiornika decyduje o opłacalności oraz kosztach budowy urządzenia. Aktualne projekty przewidują użycie stali chromowej z 9% Cr, która ma dużą wytrzymałość na pełzanie do 650&deg;C. Do budowy RPV w HTTR w Japonii została użyta stal chromowo-molibdenowa (2,25% Cr, 1% Mo). Jest ona podobna do poprzedniego typu stali, z tym, że wytrzymuje temperatury do 450&deg;C.</p>'+
    '<h1>Układy chłodzenia i kontroli reaktora</h1>'+
    '<p>W skład tych układów wchodzą m.in. osłony prętów kontrolnych, wsporniki rdzenia, kanały gazów gorących i zawory izolacyjne. Do temperatur 1100&deg;C mogą być stosowane stopy tlenków niklu lub żelaza <a href="http://pl.wikipedia.org/wiki/Utwardzanie_dyspersyjne">wzmacniane dyspersyjnie</a>. Ich wadą jest kosztowność. Materiały ogniotrwałe na bazie molibdenu, albo wolframu moga być odpowiednie powyżej 1100&deg;C, ale wykazują bardzo słabą odporność na utlenianie. Superplastyczne materiały ceramiczne, także są brane pod uwagę, ale tym przypadku problemem jest odpowiedni sposób łączenia ich z innymi elementami. We wnętrzu rdzenia, z powodu wysokich wartości strumienia neutronów, użycie metali nie jest możliwe. W tym miejscu aktualnymi rozwiązaniami są kompozyty węglowe i z włókna węglowego jako osłony prętów kontrolnych.</p>'+
    '<h1>Grafit w elementach rdzenia</h1>'+
    '<p>Grafit nie jest odporny chemicznie na działanie powietrza, albo wdarcie się wody do rdzenia - te czynniki muszą być brane w trakcie konstrukcji VHTR. Metody takie jak powlekanie elementów grafitowych pozwalają na zmniejszenie jego reaktywności chemicznej. W dodatku grafit nie jest do końca izotropowy - jego skład i zachowanie zależy od pochodzenia koksu, z którego był wytwarzany, a także od metody produkcji. Właściwości grafitu i jego możliwości wykorzystania w rdzeniu są aktualnie w trakcie badań.</p>',
  bibliography: {
    assessment: '<a href="http://www.pnnl.gov/main/publications/external/technical_reports/PNNL-20869.pdf">BK Mcdowell. JR Nickolaus. MR Mitchell. GL Swearingen.: <i>High Temperature Gas Reactors: Assessment of Applicable Codes and Standards.</i> PNNL-20869</a>',
    vhtr_rep: '<a href="http://large.stanford.edu/courses/2013/ph241/kallman1/docs/chapin.pdf"><i>A Very High Temperature Reactor: A Technical Summary</i></a>',    
  }
};