contents.safety = {
  index: 8,
  caption: "Bezpieczeństwo",
  text: '<p id="safety">Już z samego faktu, że  HTGR należą do rodziny reaktorów chłodzonych gazem wynika, że wykazują one stosunkowo wysoki poziom bezpieczeństwa. Ponadto, grafitowy rdzeń, użycie helu jako substancji chłodzącej oraz pokrytych ceramiczną warstwą kulek paliwowych sprawia, że VHTR może wytrzymać temperatury osiągane w trakcie awarii bez żadnych uszkodzeń w strukturze, czy też uwalniania produktów rozszczepialnych. Powyższe czynniki w wystarczającym stopniu zapewniają bezpieczeństwo, dlatego też aktywne a zarazem kosztowne systemy bezpieczeństwa, takie jak np. w reaktorach chłodzonych wodą są niepotrzebne.</p>'+
  '<h1>Rdzeń grafitowy</h1>'+
  '<p>Rdzeń grafitowy wykorzystywany w HTGR charakteryzuje się dużą przewodnością termiczną - zapobiega to tworzeniu się gorących miejsc w obszarze rdzenia. Ponadto duża pojemność cieplna grafitu w połączeniu z niską mocą wydzielaną w rdzeniu skutkuje stosunkowo długim opóźnieniem  we wzroście temperatury reaktora w trakcie awarii układu chłodzącego czy też podczas wzrostu reaktywności w rdzeniu. Warto podkreślić, że w trakcie braku chłodzenia, paliwo osiąga maksymalną temperaturę dopiero po kilku dniach. Zapewnia to wystarczającą ilość czasu do podjęcia stosownych kroków mających na celu wyeliminowanie danej usterki. Na rys. 1 przedstawiono zależność temperatury zbiornika i paliwa w funkcji czasu dla niedziałającego układu chłodzącego dla różnych konfiguracji rozmieszczenia prętów grafitowych w rdzeniu VHTR. W każdym z przypadków maksymalna temperatura uzyskiwana jest dopiero w przeciągu 2-3 dni.</p>'+
  '<div class="thumbnail">'+
    '<img src="img/accident_core_temp.png" alt="Temperatura reaktora w trakcie awarii" class="img-thumbnail" width="100%"/>'+
    '<div class="caption">Rys. 1. Zależność temperatury zbiornika (po lewej) i elementów paliwowych (po prawej) w czasie, po wyłączeniu układu chłodzącego reaktora. <a name="b_vhtr_rep"></a>.</div>'+
  '</div>'+
  '<p>Dodatkowo, połączenie chłodzenia helem z grafitowym moderatorem oraz kulkami paliwowymi TRISO sprawia, że rdzeń ma wysoki ujemny współczynnik reaktywności temperaturowej. Oznacza to spadek mocy i temperatury zbiornika reaktora oraz paliwa podczas awarii. Dzieje się tak dlatego, że szybkość reakcji rozszczepiania, a co za tym idzie tempo wytwarzania ciepła maleje wraz ze wzrostem temperatury rdzenia. Zostało to potwierdzone podczas testów przeprowadzonych na HTTR w Japonii. To zjawisko pozwala na stabilizację wydzielanej mocy podczas awarii oraz w przypadkach występowania niestabilności. Zatem głównym celem działań mających na celu opanowanie awarii i zapobieganie im jest ograniczanie maksymalnej temperatury rdzenia oraz paliwa. Aby wykluczyć uszkodzenia konstrukcji, projektowane są rdzenie ceramiczne i nieceramiczne o wystarczającej wytrzymałości wysokotemperaturowej. W związku z tym maksymalną temperaturę jaka może występować określa trwałość powłok kulek paliwowych. Zatem istotne jest ograniczenie maksymalnej temperatury paliwa w trakcie trwania awarii poniżej poziomu, na którym zaczyna zachodzić degradacja powłok ochronnych paliwa. Dla kulek paliwowych SiC TRISO temperatura ta wynosi 1600 &deg;C.</p>'+
  '<h1>Kapsułki paliwowe TRISO</h1>'+
  '<p>Kolejnym elementem wpływającym na bezpieczeństwo w HTGR są kulki paliwowe pokryte warstwą ceramiczną. Każda kulka paliwowa może być traktowana jako pojedynczy zbiornik ciśnieniowy, który jest w stanie utrzymać w swoim wnętrzu produkty rozszczepienia przez bardzo długi okres czasu. Skutkuje to bardzo niewielkim uwalnianiem radioizotopów z wnętrza kapsułek. Ponadto, warto zaznaczyć, że paliwo w postaci TRISO można przechowywać w niezmienionej formie nawet po jego projektowym czasie pracy. Zatem po oddzieleniu od grafitowej konstrukcji paliwa, stanowią one idealną końcową formę odpadów. W porównaniu z reaktorami ciekłowodnymi, HTGR potrzebują znacznie mniej przestrzeni do składowania zużytego paliwa.</p>'+
  '<h1>Konstrukcja reaktora</h1>'+
  '<p>Kolejnym aspektem zwiększającym bezpieczeństwo wewnętrzne HTGR jest chłodziwo helowe. Hel jest chemicznie obojętny i ma niski przekrój czynny na pochłanianie neutronów. To wyklucza komplikacje związane z napromieniowywaniem chłodziwa i jego reakcją z elementami reaktora. W porównaniu do reaktorów wodnych, hel nie zmienia stanu skupienia w zakresie temperatur powyżej temperatury pracy reaktora. To upraszcza konstrukcję mechaniczną zwiększając bezpieczeństwo. Z drugiej strony hel nie jest tak dobrą osłoną biologiczną jak woda, co ma skutek w większej ekspozycji obszarów wokół rdzenia na promieniowanie w porównaniu do reaktorów ciekłowodnych.</p>'+
  '<p>Reaktory chłodzone gazem pozwalają na przechowywanie produktów rozpadu efektywnie i są zaprojektowane tak, aby zapobiegać uwolnieniom radioizotopów bez interwencji operatora lub aktywnych systemów ochronnych. Zatem w przypadku awarii nie ma potrzeby podejmowania jakichkolwiek działań poza terenem placówki reaktora. HTGR nie wymaga szczelnej konstrukcji, zapobiegającej wyciekom i wydostawaniu się zanieczyszczeń promieniotwórczych tak jak w przypadku reaktorów ciekłowodnych. Pozwala to na zmniejszenie kosztów ich budowy. Ostatecznie, VHTR mogą być budowane w strefach przemysłowych oraz w pobliżu obszarów gęsto zaludnionych w celu dostarczania ciepła i redukcji emisji CO<sub>2</sub></p>'+
  '<h1>Proliferacja broni jądrowej</h1>'+
  '<p>Reaktory wysokotemperaturowe są także zabezpieczeniem przed proliferacją broni jądrowej. VHTR ma niską gęstość mocy w rdzeniu i niską moc w stosunku do zwykłych reaktorów wodnych. Ma to skutek w małej ilości zapasu rozszczepialnego paliwa oraz jego bardzo rozcieńczonej postaci. Dodatkowo kapsułki TRISO są trudne do przetworzenia. Każda z nich ma rozmiar od 0,65 do 0,85 mm, a całkowicie załadowany rdzeń zawiera ich około miliarda. Reprocessing paliwa jest skomplikowany: na początku grafitowe elementy muszą zostać rozbite, aby dostać się do kapsułek, a następnie TRISO muszą zostać pozbawione powłok ochronnych, co dopiero umożliwia dostęp do materiałów rozszczepialnych. Jakkolwiek, te właściwości kapsułek nie uniemożliwiają reprocessingu, ale znacznie go utrudniają.</p>',
  bibliography: {
    vhtr_rep: '<a href="http://large.stanford.edu/courses/2013/ph241/kallman1/docs/chapin.pdf"><i>A Very High Temperature Reactor: A Technical Summary</i></a>',
    tachibana: '<a href="http://www.batan.go.id/ptrkn/file/MetNet/htr/referensi/Safety%20demonstration%20test%20using%20HTTR%202004.pdf">Tachibana, Yukio, et al.: <i>Safety Demonstration Tests using High Temperature Engineering Test Reactor (HTTR).</a></i>',
    proli_treaty: '<a href="http://www.iaea.org/Publications/Documents/Infcircs/Others/infcirc140.pdf"><i>Treaty on the non-proliferation of nuclear weapons</i> - International Atomic Energy Agency</a>',
  }
};