contents.synergy = {
  index: 10,
  caption: "Program synergii węglowo-jądrowej w polsce",
  text: '<p id="synergy">Paliwa kopalne mają wspólną wadę: ich używanie w procesach przemysłowych powoduje zwiększanie emisji CO<sub>2</sub> do atmosfery. Dodatkowo są surowcami nieodnawialnymi, czyli dostępna ich ilość jest ograniczona. Jeżeli energetyka jądrowa będzie się rozwijać w tempie przewidzianym przez World Energy Council, w 21-szym wieku wystąpi problem z zaopatrzeniem reaktorów w rozszczepialne paliwo. Proces recyklingu plutonu może to nieco załagodzić.</p><p>Jednym z rozwiązań tych problemów jest synergistyczne wykorzystanie energii jądrowej i pochodzącej z paliw kopalnych do produkcji paliw syntetycznych. Metoda ta pozwala zaoszczędzić część surowców odpowiedzialną za dostarczanie ciepła do procesu produkcji paliwa, przez co zwiększa się efektywność produkcji. Ponadto, paliwo syntetyczne jest wolne od związków siarki i azotu, a jego proces wytwarzania cechuje się o wiele mniejszą emisją CO<sub>2</sub> niż tradycyjne metody przetwarzania paliw kopalnych. Proces synergistyczny jest to proces w którym dwa, lub więcej źródła energii (np. paliwa kopalne i energia jądrowa) są źródłem energii w procesie konwersji tych źródeł do innego nośnika energii. Do nośników energii można zaliczyć wodór cząsteczkowy, prąd elektryczny oraz węglowodory. Przykłady procesów synergistycznych takich jak produkcja wodoru i konwersja syngazu do syntetycznego paliwa, zostały opisane w poprzednich rozdziałach.</p>'+
  '<p>Niskotemperaturowa kogeneracja energii elektrycznej i termicznej z elektrowni jądrowych jest już obecna w kilku europejskich państwach, ze znakomitymi rezultatami w stosunku do kogeneracji z paliw kopalnych. Reaktory wysokotemperaturowe były testowane w Niemczech, Wielkeij Brytanii i USA. Obecnie reaktory testowe działają w Japonii i Chinach. Polska i Holandia wyraziły wsparcie dla rozwoju technologii jądrowej kogeneracji. Polska, aktualnie duży konsument węgla, finansuje narodowy projekt HTRPL budując drogę do demonstracji kogeneracji energii w elektrowniach wysokotemperaturowych w celu zmniejszenia emisji CO<sub>2</sub> i zwiększenia swojej konkurencyjności. Jednym z głównych celów tego projektu jest zbadanie warunków wykorzystania reaktorów wysokotemperaturowych przez polski przemysł oraz określenie optymalnego systemu wykorzystania wysokotemperaturowego ciepła do zasilania procesów technologicznych i do produkcji energii elektrycznej. W projekcie uczestniczą: PROCHEM S.A., TAURON Polska Energia S.A., KGHM Polska Miedź S.A., Środowiskowe Laboratorium Ciężkich Jonów - Uniwersytet Warszawski, Pomorska Specjalna Strefa Ekonomiczna sp. z o.o., Narodowe Centrum Badań Jądrowych, Instytut Techniki Cieplnej na Wydziale Inżynierii Środowiska i Energetyki Politechniki Śląskiej, Główny Instytut Górnictwa, Instytut Chemicznej Przeróbki Węgla oraz Instytut Nawozów Sztucznych.</p>'+
  '<p>Narodowe Centrum Badań jądrowych rozpoczęło projekt mający na celu zbadanie możliwości wykorzystania reaktorów do produkcji oprócz energii elektrycznej także ciepła procesowego. 10 października 2013 w Warszawie zainaugurowano projekt badawczy NC2I-R (Nuclear Cogeneration Industrial Initiative - Research). Polska obecnie zużywa około 14 mld. m<sup>3</sup> gazu ziemnego rocznie, pochodzącego głównie z importu. Zakłady chemiczne zużywają go 15% - wydają się one potencjalnymi odbiorcami gazu syntetycznego. Istnieje nadzieja, że Polska będzie jednym z pierwszych beneficjentów tego programu, i da to naszemu krajowi możliwość uniezależnienia się od ropy, czy gazu ziemnego. Głównym celem NC2I jest uruchomienie w przeciągu 10 lat prototypu reaktora umożliwiającego kogenerację energii. Da to liczącą się pozycję Europie na arenie międzynarodowej i włączy technologie niskiej emisji CO<sub>2</sub> w obszary przemysłu z dużym zapotrzebowaniem energetycznym. Plan demonstracji i uruchomienia reaktora wysokotemperaturowego przez NC2I w Europie jest przedstawiony na rys.&nbsp;1.</p>'+
    '<div class="thumbnail">'+
    '<img src="img/roadmap.jpg" alt="Mapa drogowa NC2I" class="img-thumbnail" width="100%"/>'+
    '<div class="caption">Rys. 1. Plan rozwoju technologii reaktorów wysokotemperaturowych w Europie. Planowane jest uruchomienie pierwszego reaktora po 10 latach <a name="b_snetp"></a>.</div>'+
  '</div>',
  bibliography: {
    synergy: '<a href="http://www.ne.jp/asahi/mh/u/HoriSynergyOECD.pdf">M. Hori et al.<i>Synergy of Fossil Fuelsand Nuclear Energy for the Energy Future</i></a>',
    snetp: '<a href="http://www.snetp.eu/www/snetp/index.php?option=com_content&view=article&id=110&Itemid=69">http://www.snetp.eu/www/snetp/index.php?option=com_content&view=article&id=110&Itemid=69</a>',
    nuclearpl: '<a href="http://nuclear.pl/wiadomosci,news,13030401.html">Spotkanie w AGH poświęcone projektowi HTRPL</a>',
    ncbj: '<a href="http://www.ncbj.gov.pl/node/2789">NC2I-R – rusza pierwszy projekt koordynowany przez Polskę w ramach programu Euratom</a>'
  }
};